[package]
name = "chronoutil"
version = "0.1.1"
authors = ["olliemath <oliver@suade.org>"]
edition = "2018"
description = "Powerful extensions to rust's Chrono crate"
repository = "https://github.com/olliemath/chronoutil"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"chrono" = "^0.4"
